language: ruby
rvm: 2.2.2
env: RAILS_ENV=test
script:
  - bundle exec rspec
#addons:
#  postgresql: "9.5.2"
#  code_climate:
#    repo_token: 57bd7c06635632016619f56e85e0f745cf62d3d3
#before_script:
#  - psql -c 'create database travis_ci_test;' -U postgres
#  - bundle exec rake db:migrate
#install: bundle install --jobs=3 --retry=3